DROP TABLE IF EXISTS EMPLOYEES;
 
CREATE TABLE EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  salary VARCHAR(30) NOT NULL,
  department VARCHAR(30) NOT NULL,
  position VARCHAR(50) NOT NULL,
  email_address VARCHAR(30) NOT NULL,
  contact_number VARCHAR(10) NOT NULL,
  picture VARCHAR(250) DEFAULT NULL
);
